name: 'Install PHIVE tools'
author: 'Yuta Nagamiya'
description: 'Downloads PHIVE, installs tools, and uploads them to the artifact store'
inputs:
  phive-arguments:
    description: 'Additional arguments to pass to PHIVE'
    required: false
branding:
  icon: 'download'
  color: 'purple'
runs:
  using: 'composite'
  steps:
    - name: 'Install PHIVE'
      run: ${{ github.action_path }}/src/utils/retry.sh ${{ github.action_path }}/src/phive/install.sh
      shell: 'bash'
      # TODO: When "uses" becomes available, replace the above with the following
      #    - name: 'Install PHIVE'
      #      uses: 'nick-invision/retry@v2'
      #      with:
      #        timeout_minutes: 10
      #        max_attempts: 3
      #        command: |
      #          wget -O phive.phar https://phar.io/releases/phive.phar
      #          wget -O phive.phar.asc https://phar.io/releases/phive.phar.asc
      #          gpg --keyserver pool.sks-keyservers.net --recv-keys 0x9D8A98B29B2D5D79
      #          gpg --verify phive.phar.asc phive.phar
    - name: 'Install tools'
      run: ${{ github.action_path }}/src/utils/retry.sh ${{ github.action_path }}/src/phive/install-tools.sh ${{ inputs.phive-arguments }}
      shell: 'bash'
      # TODO: When "uses" becomes available, replace the above with the following
      #    - name: 'Install tools'
      #      uses: 'nick-invision/retry@v2'
      #      with:
      #        timeout_minutes: 10
      #        max_attempts: 3
      #        command: |
      #          yes | \
      #          php phive.phar --no-progress install \
      #            --copy
      # TODO: When "uses" is available, add the following
      #    - name: 'Upload tools to artifact store'
      #      uses: 'actions/upload-artifact@master'
      #      with:
      #        name: 'tools'
      #        path: 'tools'
